typography_spectrum: 0.06225472642108798
color:
  brandStrength: 0.21508083143271506
  lightness: 0.7766801214311272
  saturation: 0.46187975513748825
  rhythmicContrast: 0.6988738363143057
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.06196308718062937
name: ULTRA
navigation:
  - name: Production Co.
    url: www.speakeasyproject.com
    type: external
  - name: Official website
    url: www.ultradocumentary.com
    type: external
title: Everybody hurts
description: Everybody hurts
